version: '3'
services:
  web:
    image: nginx:1.20.2
    ports:
      - "8081:80"
    volumes:
      - ./html:/html
      - ./nginx/nginx.conf:/etc/nginx/default.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      vpcbr:
        ipv4_address: 10.1.0.2

  php:
    build: ./php/
    volumes:
      - ./html:/html
    links:
      - db
    networks:
      vpcbr:
        ipv4_address: 10.1.0.3

  db:
    image: mariadb:10.6.8
    env_file:
      - ./mariadb/.env
    restart: "no"
    ports:
      - 3301:3306
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/conf.d:/etc/mysql/conf.d
    networks:
      vpcbr:
        ipv4_address: 10.1.0.4

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.0.0/16
         gateway: 10.1.0.1